- hosts: nodes
  tasks:
    - name: Define parameters in GRUB config file
      lineinfile:
        path: /etc/default/grub
        regexp: '^GRUB_CMDLINE_LINUX='
        line: GRUB_CMDLINE_LINUX="no_timer_check console=tty0 console=ttyS0,115200n8 net.ifnames=0 biosdevname=0 elevator=noop"
        backrefs: yes

    - name: Load config to GRUB 
      command: grub2-mkconfig -o /boot/grub2/grub.cfg
   
