- hosts: nodes
  tasks:
    - name: Apache | Ensure Apache is installed
      yum:
         name: httpd
         state: present
    - name: Apache | Copy a index.html
      copy:
         src: index.html
         dest: /var/www/html/index.html
         owner: root
         group: root
         mode: '0644'
    - name: Apache | Ensure Apache is started and enabled to start at boot
      service:
        name: httpd
        state: started
        enabled: yes
    - name: FireWall | Permit traffic for Apache service
      firewalld:
        service: http
        permanent: yes
        state: enabled
